#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
set -x
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_20/bin/:$PATH
java -version
cd $OPENSHIFT_REPO_DIR
java -jar diy/todoapp.jar &