#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH
# The logic to stop your application should be put in this script.
kill `ps -ef | grep todoapp | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0